[package]
name = "clique"
version = "0.1.0"
authors = ["alexander <khlebuschev@physics.msu.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "clique"
crate_type = ["dylib"]
